version: '3.1'

networks: 
  ts-backend:
    driver: 'bridge'

services: 
  app:
    image: node:15.3.0-slim
    container_name: 'ts-app'
    ports: 
      - 3333:3333
    working_dir: '/home/node/app'
    volumes: 
      - ./:/home/node/app
    networks: 
      - ts-backend
    command: 
      - sh
      - -c
      -  |
        ./init.sh ${MODE}

