version: '3.1'

volumes: 
  mongo-data:
    name: ${DB_VOLUME}

networks: 
  ts-backend:
    driver: 'bridge'

services: 
  mongo:
    image: mongo
    container_name: 'ts-mongo'
    restart: 'always'
    ports: 
      - 27017:27017
    volumes: 
      - mongo-data:/data/db
    networks: 
      - ts-backend

  app:
    image: node:15.4.0-alpine
    container_name: 'ts-app'
    ports: 
      - 3333:3333
    working_dir: '/home/node/app'
    volumes: 
      - ./:/home/node/app
    networks: 
      - ts-backend
    command: 
      - sh
      - -c
      -  |
        ./init.sh ${MODE}

